"""empty message

Revision ID: 5d99d6202ea5
Revises: 9d0e2fb8e94a
Create Date: 2023-07-04 14:55:55.974255

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5d99d6202ea5'
down_revision = '9d0e2fb8e94a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('journal_prompts', schema=None) as batch_op:
        batch_op.drop_column('completed_at')

    with op.batch_alter_table('nudge_prompts', schema=None) as batch_op:
        batch_op.drop_column('completed_at')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('nudge_prompts', schema=None) as batch_op:
        batch_op.add_column(sa.Column('completed_at', sa.DATETIME(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True))

    with op.batch_alter_table('journal_prompts', schema=None) as batch_op:
        batch_op.add_column(sa.Column('completed_at', sa.DATETIME(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True))

    # ### end Alembic commands ###
