"""empty message

Revision ID: 9d0e2fb8e94a
Revises: 315f2eb99ec1
Create Date: 2023-07-04 14:50:37.364088

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9d0e2fb8e94a'
down_revision = '315f2eb99ec1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('completed_prompts', schema=None) as batch_op:
        batch_op.drop_column('completed_at')

    with op.batch_alter_table('journal_prompts', schema=None) as batch_op:
        batch_op.add_column(sa.Column('completed_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True))

    with op.batch_alter_table('nudge_prompts', schema=None) as batch_op:
        batch_op.add_column(sa.Column('completed_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('nudge_prompts', schema=None) as batch_op:
        batch_op.drop_column('completed_at')

    with op.batch_alter_table('journal_prompts', schema=None) as batch_op:
        batch_op.drop_column('completed_at')

    with op.batch_alter_table('completed_prompts', schema=None) as batch_op:
        batch_op.add_column(sa.Column('completed_at', sa.DATETIME(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True))

    # ### end Alembic commands ###
